name: communicado
description: "A client to server communication plugin with easy to use."
version: 0.0.1
homepage: https://github.com/abulkalamjaan/communicado.git
license: Apache-2.0
author: Abul Kalam Jaan
author_email: abul@abulkalam.dev

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  dio: ^4.0.0
  connectivity_plus: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true